oneplus9: DeviceSettings: Fix dependency conflict
Log:
device/oneplus/oneplus9/DeviceSettings/src/org/lineageos/device/DeviceSettings/SliderControllerBase.java:25: error: package lineageos.providers does not exist
import lineageos.providers.LineageSettings;
                          ^
device/oneplus/oneplus9/DeviceSettings/src/org/lineageos/device/DeviceSettings/SliderControllerBase.java:99: error: package LineageSettings does not exist
                LineageSettings.System.TOUCHSCREEN_GESTURE_HAPTIC_FEEDBACK, 1, UserHandle.USER_CURRENT) != 0;
                               ^
device/oneplus/oneplus9/DeviceSettings/src/org/lineageos/device/DeviceSettings/SliderControllerBase.java:98: error: package LineageSettings does not exist
        boolean enabled = LineageSettings.System.getIntForUser(mContext.getContentResolver(),
                                         ^
device/oneplus/oneplus9/DeviceSettings/src/org/lineageos/device/DeviceSettings/Startup.java:34: error: package lineageos.content.Intent does not exist
        if (lineageos.content.Intent.ACTION_INITIALIZE_LINEAGE_HARDWARE.equals(action)) {
                                    ^
4 errors

Change-Id: c1ea719c3663a16f55fb999ffbbd7e6dfe41d072
Signed-off-by: TogoFire <togofire@mailfence.com>