oneplus9: DeviceSettings: define LOCAL_OPTIONAL_USES_LIBRARIES
fixes:
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: []
	- optional libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- tags in the manifest (out/target/common/obj/APPS/DeviceSettings_intermediates/manifest/AndroidManifest.xml):
		<uses-library android:name="androidx.window.extensions" android:required="false"/>
		<uses-library android:name="androidx.window.sidecar" android:required="false"/>

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: Iaaf1c8b0ca7946d06a294b7e94500e881b8c1fdf