oneplus9: vintf: Remove duplicated vendor.lineage.touch entry
Log:
getDeviceHalManifest: status from fetching VINTF information: -2147483648
getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/vendor.lineage.touch@1.0-service.oplus.xml: HAL "vendor.lineage.touch" has a conflict: Conflicting FqInstance: @1.0::ITouchscreenGesture/default (from /vendor/etc/vintf/manifest.xml) vs. @1.0::ITouchscreenGesture/default (from /vendor/etc/vintf/manifest/vendor.lineage.touch@1.0-service.oplus.xml). Check whether or not multiple modules providing the same HAL are installed.
Unable to print HALs from new FCMs: no device HAL manifest.
ERROR: No such device: No device manifest file from device or from update package
No device manifest.
No device HAL manifest
Missing device manifest.: No such file or directory: No such device

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I858fac0af46341ea45cddfecacb6d2ab2d1cf9aa