oneplus9: Build and import some hals
* Display hal
* Wifi Display hal (qcom wfd)
* Define TARGET_GRALLOC_HANDLE_HAS_RESERVED_SIZE
* Audio hal
* audio_effects.xml - already exists in vendor
* Move Properties
* Media / av
* Bluetooth
* Switch BtAudio to AIDL
* Use 2.0 for bluetooth.audio (Fixes bluetooth issues with calls).
* Import Lineage init and Qcom init / and keep only lahaina
* Adreno r
* QSEEComD QTI
* Alarm QTI
* USB QTI - ref: https://github.com/LineageOS/android_vendor_qcom_opensource_usb
* Telephony QTI & Bring back datastatusnotification
* Move AtFwd hal from device to framework manifest
* Build android.hardware.power@1.2.vendor
* Build qti perf hal vendor.qti.hardware.perf@2.2.vendor
* Move display props to vendor.prop
* Introduce gps-legacy qti -ref: https://github.com/AOSPA/android_hardware_qcom_gps/commits/uvite-legacy-component/
https://github.com/AOSPA/android_device_qcom_common/blob/82c1151d7bc4887266ec0d4eff8089793ed49d74/components.mk#L92-L100

- Remove AtFwd hal manifest
FAILED: ninja: 'system/libhidl/vintfdata/config/telephony/framework_manifest.xml', needed by '/out/target/product/oneplus9/gen/ETC/system_manifest.xml_intermediates/manifest.xml', missing and no known rule to make it
FAILED: ninja: 'system/libhidl/vintfdata/configs/telephony/atcmdfwd-saidl.xml', needed by '/out/target/product/oneplus9/gen/ETC/system_ext_manifest.xml_intermediates/manifest.xml', missing and no known rule to make it

- Remove duplicate sysprop usb
Log:
out/target/product/oneplus9/vendor/build.prop )"
error: found duplicate sysprop assignments:
vendor.usb.use_ffs_mtp=1
vendor.usb.use_ffs_mtp=0
out/target/product/oneplus9/vendor/build.prop ) && (echo \"# end of file\" >> /out/target/product/oneplus9/vendor/build.prop )"
error: found duplicate sysprop assignments:
vendor.usb.qdss.inst.name=qdss_sw
vendor.usb.qdss.inst.name=qdss

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I2ea8a98f32f7bf939f9ac19b2c541bebc9338139