oneplus9: DeviceSettings: RotationController: include caller information
device/oneplus/sm8350-common/DeviceSettings/src/org/lineageos/device/DeviceSettings/slider/RotationController.java:69: error: method freezeRotation in interface IWindowManager cannot be applied to given types;
                wm.freezeRotation(rotation);
                  ^
  required: int,String
  found:    int
  reason: actual and formal argument lists differ in length
device/oneplus/sm8350-common/DeviceSettings/src/org/lineageos/device/DeviceSettings/slider/RotationController.java:71: error: method thawRotation in interface IWindowManager cannot be applied to given types;
                wm.thawRotation();
                  ^
  required: String
  found:    no arguments
  reason: actual and formal argument lists differ in length

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I0aea12003cf2f397b0499ef293749f6291a148ec